# Poetry Configuration
# This file contains Poetry-specific configuration settings

[virtualenvs]
# Virtual environment configuration
in-project = true



# Additional Poetry settings can be added here as needed
# For example:
# [tool.poetry.dependencies]
# python = "^3.8"
# 
# [tool.poetry.dev-dependencies]
# pytest = "^6.0"
